"""
BORDER OPTICS — Combined Maps & Plots PDF

Compiles every static figure (outputs/figures/*.png) and a static render of
every interactive Folium map (outputs/figures/static_map_renders/*.png,
generated by build_static_map_renders.py) into a single PDF, one image per
page (auto portrait/landscape based on the image's own aspect ratio),
preceded by a cover page listing every item.

The interactive Folium maps themselves stay interactive on the live
dashboard (Interactive Maps page) — this PDF exists for offline/print
reference only, so each map's page notes that the live version is
clickable/zoomable.
"""

import os
from PIL import Image
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

OUT_PATH = "BORDER_OPTICS_Maps_and_Plots.pdf"
BG = (10, 10, 10)
ACCENT = (215, 165, 60)
TEXT = (240, 240, 235)

# NOTE: mapping here MUST match Research_Paper.md's actual (renumbered)
# figure sequence, not the source PNG filename numbers — the filenames were
# assigned in generation order (Development_Log.md, Entries 5 and 7), which
# is not the same as the paper's reading-order sequence. Cross-checked
# against every "Figure N." caption in Research_Paper.md before finalizing.
ITEMS = [
    ("outputs/figures/01_ndbi_change_distribution.png",
     "Figure 1 — NDBI Change Distribution",
     "Full-year vs summer-matched composites, all geocoded villages."),
    ("outputs/figures/04_state_mean_ndbi_change.png",
     "Figure 2 — State-Wise Mean Built-Up Area Change",
     "Summer-matched composite, by state."),
    ("outputs/figures/06_lights_change_distribution.png",
     "Figure 3 — Distribution of Night-Lights Change",
     "Summer-matched composite, all geocoded villages."),
    ("outputs/figures/05_state_mean_lights_change.png",
     "Figure 4 — State-Wise Mean Night-Lights Change",
     "Summer-matched composite, by state."),
    ("outputs/figures/02_state_change_vs_budget.png",
     "Figure 5 — State-Level Built-up Change vs Sanctioned Budget",
     "Summer-matched NDBI change, Arunachal Pradesh vs Uttarakhand (RQ2)."),
    ("outputs/figures/03_h3_border_distance_vs_lights.png",
     "Figure 6 — H3: Border Distance vs NDBI and Night-Light Change",
     "Full-year vs summer-matched composites."),
    ("outputs/figures/07_robustness_summary.png",
     "Figure 7 — Robustness Summary",
     "Significance of all four core tests under both compositing windows."),
    ("outputs/figures/08_control_group_did_effect.png",
     "Figure 8 — Control-Group Difference-in-Differences Effect",
     "Treated-vs-control gap in change, district fixed effects, both compositing windows (H4)."),
    ("outputs/figures/09_multiyear_trend.png",
     "Figure 9 — Three-Point Multi-Year Trend",
     "Mean NDBI and night-lights radiance at 2021, 2023, and 2025, both compositing windows."),
    ("outputs/figures/10_buffer_sensitivity.png",
     "Figure 10 — Buffer-Radius Sensitivity",
     "NDBI significance at 250m, 500m, and 1km buffer radii, summer window."),
    ("outputs/figures/static_map_renders/map_state_overview.png",
     "Map 1 — Village Sample Overview",
     "All 258 geocoded villages, colored by state. Interactive version: dashboard → Interactive Maps → State Overview."),
    ("outputs/figures/static_map_renders/map_ndbi_fullyear.png",
     "Map 2 — NDBI Change (Full-Year Composite)",
     "Interactive version: dashboard → Interactive Maps → Built-Up Change — Full-Year Composite."),
    ("outputs/figures/static_map_renders/map_ndbi_summer.png",
     "Map 3 — NDBI Change (Summer-Matched Composite)",
     "Interactive version: dashboard → Interactive Maps → Built-Up Change — Summer-Matched Composite."),
    ("outputs/figures/static_map_renders/map_lights_change.png",
     "Map 4 — Night-Lights Change",
     "Interactive version: dashboard → Interactive Maps → Night-Lights Change."),
    ("outputs/figures/static_map_renders/map_border_distance.png",
     "Map 5 — Village Proximity to Border/LAC",
     "Interactive version: dashboard → Interactive Maps → Border / LAC Proximity."),
]

PAGE_W, PAGE_H = letter


def draw_cover(c):
    c.setFillColorRGB(*[v / 255 for v in BG])
    c.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)

    c.setFillColorRGB(*[v / 255 for v in ACCENT])
    c.setFont("Helvetica-Bold", 26)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 140, "BORDER OPTICS")

    c.setFillColorRGB(*[v / 255 for v in TEXT])
    c.setFont("Helvetica", 15)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 170, "Maps & Plots")
    c.setFont("Helvetica", 10)
    c.drawCentredString(PAGE_W / 2, PAGE_H - 190, "Satellite-Based Verification Framework for India's Vibrant Villages Programme (VVP-I)")

    y = PAGE_H - 250
    c.setFont("Helvetica-Bold", 11)
    c.drawString(72, y, "Contents")
    y -= 22
    c.setFont("Helvetica", 10)
    for i, (_, title, _) in enumerate(ITEMS, start=1):
        c.drawString(84, y, f"{i}.  {title}")
        y -= 17

    c.setFont("Helvetica-Oblique", 8)
    c.setFillColorRGB(*[v / 255 for v in (150, 150, 150)])
    c.drawCentredString(PAGE_W / 2, 50,
        "The five Map pages are static renders for print/offline reference. "
        "Live versions on the dashboard are interactive (pan, zoom, click-to-inspect).")
    c.showPage()


def draw_image_page(c, path, title, caption):
    img = Image.open(path)
    w, h = img.size
    landscape_page = w > h

    page_size = landscape(letter) if landscape_page else letter
    c.setPageSize(page_size)
    pw, ph = page_size

    c.setFillColorRGB(*[v / 255 for v in BG])
    c.rect(0, 0, pw, ph, fill=1, stroke=0)

    margin = 40
    title_h = 50
    caption_h = 40
    avail_w = pw - 2 * margin
    avail_h = ph - title_h - caption_h - 2 * margin

    scale = min(avail_w / w, avail_h / h)
    draw_w, draw_h = w * scale, h * scale
    x = (pw - draw_w) / 2
    y = margin + caption_h

    c.drawImage(path, x, y, width=draw_w, height=draw_h)

    c.setFillColorRGB(*[v / 255 for v in ACCENT])
    c.setFont("Helvetica-Bold", 13)
    c.drawCentredString(pw / 2, ph - margin - 20, title)

    c.setFillColorRGB(*[v / 255 for v in TEXT])
    c.setFont("Helvetica", 9)
    c.drawCentredString(pw / 2, margin + 18, caption)

    c.showPage()


def main():
    c = canvas.Canvas(OUT_PATH, pagesize=letter)
    draw_cover(c)
    for path, title, caption in ITEMS:
        if not os.path.exists(path):
            print(f"WARNING: missing {path}, skipping")
            continue
        draw_image_page(c, path, title, caption)
    c.save()
    print(f"Saved {OUT_PATH}")


if __name__ == "__main__":
    main()
