import argparse
import os
import time

import ee
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

S2_COLLECTION = "COPERNICUS/S2_SR_HARMONIZED"
VIIRS_COLLECTION = "NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG"
BUFFER_RADIUS_M = 500  # same as every other extraction in this study

VILLAGE_PATHS = {
    "treated": "data/processed/border_optics_master_villages.csv",
    "control": "data/processed/border_optics_control_villages.csv",
}

# Single-period baseline windows -- one composite per village, not a
# before/after pair, since 2019 IS the "before" of this specific placebo
# comparison (2019 vs. the existing 2021 "before" of the main study).
WINDOWS = {
    "full_year": ("2019-01-01", "2020-01-01"),
    "summer": ("2019-06-01", "2019-10-01"),
}

OUT_PATHS = {
    ("treated", "full_year"): "data/processed/border_optics_treated_pretreatment_fullyear.csv",
    ("treated", "summer"): "data/processed/border_optics_treated_pretreatment_summer.csv",
    ("control", "full_year"): "data/processed/border_optics_control_pretreatment_fullyear.csv",
    ("control", "summer"): "data/processed/border_optics_control_pretreatment_summer.csv",
}

OUTCOME_COLS = ["ndbi_2019", "lights_2019", "ndbi_2019_image_count", "lights_2019_image_count"]


def init_ee():
    project = os.environ.get("EE_PROJECT")
    try:
        ee.Initialize(project=project)
    except Exception:
        ee.Authenticate()
        ee.Initialize(project=project)


def mask_s2_clouds(image):
    qa = image.select("QA60")
    cloud_bit_mask = 1 << 10
    cirrus_bit_mask = 1 << 11
    mask = qa.bitwiseAnd(cloud_bit_mask).eq(0).And(qa.bitwiseAnd(cirrus_bit_mask).eq(0))
    return image.updateMask(mask).divide(10000)


def ndbi_for_period(buffered_geom, start, end):
    collection = (
        ee.ImageCollection(S2_COLLECTION)
        .filterBounds(buffered_geom)
        .filterDate(start, end)
        .map(mask_s2_clouds)
    )
    count = collection.size().getInfo()
    if count == 0:
        return None, 0
    composite = collection.median()
    ndbi_image = composite.normalizedDifference(["B11", "B8"]).rename("NDBI")
    stats = ndbi_image.reduceRegion(
        reducer=ee.Reducer.mean(), geometry=buffered_geom, scale=10, maxPixels=1e9,
    ).getInfo()
    return stats.get("NDBI"), count


def lights_for_period(buffered_geom, start, end):
    collection = ee.ImageCollection(VIIRS_COLLECTION).filterBounds(buffered_geom).filterDate(start, end)
    count = collection.size().getInfo()
    if count == 0:
        return None, 0
    composite = collection.select("avg_rad").mean()
    stats = composite.reduceRegion(
        reducer=ee.Reducer.mean(), geometry=buffered_geom, scale=500, maxPixels=1e9,
    ).getInfo()
    return stats.get("avg_rad"), count


def _load_with_resume(group, out_path):
    """Treated: village_id is stable (master list never regenerated), so a
    plain village_id-based resume is safe, matching
    extract_dynamicworld_built.py's own convention for the treated side.
    Control: border_optics_control_villages.csv gets fully regenerated by
    select_control_villages.py with village_id reassigned from scratch each
    time (Development Log Entry 22 already found and fixed this exact
    footgun in extract_control_satellite_data.py) -- resume by matching
    rounded (latitude, longitude) coordinate pairs instead, and only if the
    checkpoint's coordinate set matches the current village list exactly.
    """
    villages = pd.read_csv(VILLAGE_PATHS[group])
    for col in OUTCOME_COLS:
        if col not in villages.columns:
            villages[col] = None

    if not os.path.exists(out_path):
        return villages

    existing = pd.read_csv(out_path)

    if group == "treated":
        if "village_id" in existing.columns:
            lookup = existing.set_index("village_id")[
                [c for c in OUTCOME_COLS if c in existing.columns]
            ].to_dict("index")
            for i, vid in zip(villages.index, villages["village_id"]):
                values = lookup.get(vid)
                if values:
                    for col in OUTCOME_COLS:
                        if col in values:
                            villages.at[i, col] = values[col]
            print(f"Resuming from existing checkpoint: {out_path} ({len(existing)} rows, matched by village_id)")
        return villages

    # group == "control": coordinate-based resume, per the docstring above.
    current_coords = set(zip(villages["latitude"].round(6), villages["longitude"].round(6)))
    existing_coords = (
        set(zip(existing["latitude"].round(6), existing["longitude"].round(6)))
        if {"latitude", "longitude"}.issubset(existing.columns) else set()
    )
    if not (existing_coords and existing_coords == current_coords):
        print(f"  Existing checkpoint at {out_path} ({len(existing)} rows) doesn't match the current "
              f"{len(villages)}-village control list -- starting fresh rather than reusing stale data.")
        return villages

    lookup = existing.copy()
    lookup["_coord_key"] = list(zip(lookup["latitude"].round(6), lookup["longitude"].round(6)))
    lookup_dict = lookup.set_index("_coord_key")[
        [c for c in OUTCOME_COLS if c in lookup.columns]
    ].to_dict("index")
    villages_keys = list(zip(villages["latitude"].round(6), villages["longitude"].round(6)))
    for i, key in zip(villages.index, villages_keys):
        values = lookup_dict.get(key)
        if values:
            for col in OUTCOME_COLS:
                if col in values:
                    villages.at[i, col] = values[col]
    print(f"Resuming from existing checkpoint: {out_path} ({len(existing)} rows, matched by coordinate)")
    return villages


def extract(group, window_key, checkpoint_every=10):
    start, end = WINDOWS[window_key]
    out_path = OUT_PATHS[(group, window_key)]
    villages = _load_with_resume(group, out_path)

    print(f"--- Extracting {window_key} 2019 pre-treatment baseline, group='{group}' ---")
    print(f"Period: {start} to {end}")
    print(f"{len(villages)} villages to process")

    for i, row in villages.iterrows():
        if all(pd.notna(row.get(c)) for c in OUTCOME_COLS):
            continue  # already extracted (resume support)

        point = ee.Geometry.Point([row["longitude"], row["latitude"]])
        buffered_geom = point.buffer(BUFFER_RADIUS_M)

        ndbi, ndbi_n = ndbi_for_period(buffered_geom, start, end)
        lights, lights_n = lights_for_period(buffered_geom, start, end)

        villages.at[i, "ndbi_2019"] = ndbi
        villages.at[i, "lights_2019"] = lights
        villages.at[i, "ndbi_2019_image_count"] = ndbi_n
        villages.at[i, "lights_2019_image_count"] = lights_n

        if (i + 1) % checkpoint_every == 0:
            villages.to_csv(out_path, index=False)
            print(f"  {i + 1}/{len(villages)} villages processed...")

        time.sleep(0.2)  # be polite to the Earth Engine API

    villages.to_csv(out_path, index=False)
    n_valid = villages.dropna(subset=["ndbi_2019"]).shape[0]
    print(f"Done. {n_valid}/{len(villages)} villages have valid 2019 NDBI data.")
    print(f"Saved to {out_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract a 2019 pre-treatment baseline (NDBI, VIIRS lights) for a genuine parallel-pre-trends placebo test (Section 7.5)."
    )
    parser.add_argument("--group", choices=["treated", "control"], required=True)
    parser.add_argument("--window", choices=["full_year", "summer"], required=True)
    args = parser.parse_args()

    init_ee()
    extract(args.group, args.window)
